name: "Amber Language Action Test"
on: [push, pull_request]

jobs:      
  test-default:
    defaults:
      run:
        working-directory: test/default-entrypoint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            test/default-entrypoint
          sparse-checkout-cone-mode: false

      - name: Compile Amber Code
        uses: arch-fan/amber-action@main

      - name: Run compiled script and verify output
        run: |
          expected="Hello, World!"
          actual=$(./main.sh)
          echo "Expected: $expected"
          echo "Actual: $actual"
          if [ "$actual" != "$expected" ]; then
            echo "Error: Output mismatch"
            exit 1
          fi
